### ISSUE TITLE
book names in translation

### ISSUE THREAD

**Issue by missweizhang** [getbible/v2#10]
Hi, Is there a way to get the names of the books of the Bible in the language/version I've selected?
I'm using v2.

**Comment by Llewellynvdm** [comment]
Okay so in version two we have a file:

In the repository
- https://github.com/getbible/v2/blob/master/cut/books
- https://github.com/getbible/v2/blob/master/cut/books.json

Same as in the API:
- https://getbible.net/v2/cut/books
- https://getbible.net/v2/cut/books.json

But yes those are not translated, but if you make a PR to this repository, with the translation in place of the English strings link the Afrikaans versions:

- https://getbible.net/v2/aov/books
- https://getbible.net/v2/aov/books.json

You will have the needed endpoint... to you can do for any translation currently in the repository.

We have noticed that some translations where removed a few months ago... but they are still in our API and we are planning to add them back to this repository. So here is the complete API translation/version list:

https://getbible.net/v2/translations.json

**Comment by missweizhang** [comment]
Thank you so much for writing back.  Do you know why they have removed those translations?  

Here are all the Chinese Book names on Biblegateway.com

Simplified Chinese
https://www.biblegateway.com/versions/Chinese-Union-Version-Modern-Punctuation-Simplified-CUVMPS/#booklist

Traditional Chinese
https://www.biblegateway.com/versions/Chinese-Union-Version-Modern-Punctuation-Traditional-CUVMPT/#booklist

Your API is very helpful, thanks so much for the good work!

**Comment by Llewellynvdm** [comment]
You're very welcome. Tell me, have you read over this repository? https://github.com/getbible/v2_builder

You will see that that is the build script of the API, and it broke about 7 months ago, but yesterday [I fixed the problem](https://github.com/getbible/v2_builder/commits/master), and ran a new build and as you will see all the Bibles are back.

The real issue was that the script broke when a download was no longer found at its original location, and then instead of continuing with other versions it just stopped downloading. But this issue has now been resolved, and the API is stable again.

Okay so [in the builder](https://github.com/getbible/v2_builder/blob/master/src/sword_to_json.py#L104) we load the book name from three sources at this point. These three sources are:
- [API.v1](https://github.com/getbible/v2_builder/blob/master/src/sword_to_json.py#L60)
- [Local file](https://github.com/getbible/v2_builder/blob/master/src/sword_to_json.py#L30)
- [From the actual crosswire module](https://github.com/getbible/v2_builder/blob/master/src/sword_to_json.py#L48)

So my idea is to add a fourth source, which can also be a local file, but targeted per/language. I will do this, all I need is the file.

So with this I need **your** help, as I can't read Chinese, someone who can should build the json object. And the book names should be in the same [unicode](https://www.fileformat.info/info/unicode/char/7CFB/index.htm) that will look like this:

https://getbible.net/v2/cut/2.json
![image](https://user-images.githubusercontent.com/5607939/180595816-dae38c26-0a0d-4982-8385-8e2901657335.png)
```
\u4ee5\u8272\u5217\u7684\u773e\u5b50\uff0c\u5404\u5e36\u5bb6\u7737\uff0c\u548c\u96c5\u5404\u4e00\u540c\u4f86\u5230\u57c3\u53ca\u3002\u4ed6\u5011\u7684\u540d\u5b57\u8a18\u5728\u4e0b\u9762\u3002
```

Here is [a converter I found](https://r12a.github.io/app-conversion/)... not really sure if it's the correct one.
![image](https://user-images.githubusercontent.com/5607939/180595980-6dad1056-f005-4f67-ac7e-434a0f073a99.png)

Check the **JS/Java/C** option and that the []Es6 is unchecked, this gives the same encoding as seen in the API:
![image](https://user-images.githubusercontent.com/5607939/180596021-abf14c2d-3e44-4bc1-9c78-7b884c0eecbd.png)
![image](https://user-images.githubusercontent.com/5607939/180596030-581b2695-647d-4612-abb0-f561e3fbc585.png)

The file format should be as follow:
```json
{
  "1": "Genesis",
  "2": "Exodus",
  "3": "Leviticus",
  "4": "Numbers"
}
```
So the number of the book is the key, and the name of the book is the value. You can just place your json in [this website](https://jsoneditoronline.org/#left=cloud.170a4f0b3e174a5b8e8ef7a25f0c433f) and give me the share link here.

The link will look like this `https://jsoneditoronline.org/#left=cloud.170a4f0b3e174a5b8e8ef7a25f0c433f`

Let me know if you have any questions.

**Comment by missweizhang** [comment]
Traditional Chinese
{"1":"﻿創世記","2":"出埃及記","3":"利未記","4":"民數記","5":"申命記","6":"約書亞記","7":"士師記","8":"路得記","9":"撒母耳記上","10":"撒母耳記下","11":"列王紀上","12":"列王紀下","13":"歷代志上","14":"歷代志下","15":"以斯拉記","16":"尼希米記","17":"以斯帖記","18":"約伯記","19":"詩篇","20":"箴言","21":"傳道書","22":"雅歌","23":"以賽亞書","24":"耶利米書","25":"耶利米哀歌","26":"以西結書","27":"但以理書","28":"何西阿書","29":"約珥書","30":"阿摩司書","31":"俄巴底亞書","32":"約拿書","33":"彌迦書","34":"那鴻書","35":"哈巴谷書","36":"西番雅書","37":"哈該書","38":"撒迦利亞","39":"瑪拉基書","40":"馬太福音","41":"馬可福音","42":"路加福音","43":"約翰福音","44":"使徒行傳","45":"羅馬書","46":"歌林多前書","47":"歌林多後書","48":"加拉太書","49":"以弗所書","50":"腓立比書","51":"歌羅西書","52":"帖撒羅尼迦前書","53":"帖撒羅尼迦後書","54":"提摩太前書","55":"提摩太後書","56":"提多書","57":"腓利門書","58":"希伯來書","59":"雅各書","60":"彼得前書","61":"彼得後書","62":"約翰一書","63":"約翰二書","64":"約翰三書","65":"猶大書","66":"启示录"}

Simplified Chinese
{"1":"﻿创世记","2":"出埃及记","3":"利未记","4":"民数记","5":"申命记","6":"约书亚记","7":"士师记","8":"路得记","9":"撒母耳记上","10":"撒母耳记下","11":"列王纪上","12":"列王纪下","13":"历代志上","14":"历代志下","15":"以斯拉记","16":"尼希米记","17":"以斯帖记","18":"约伯记","19":"诗篇","20":"箴言","21":"传道书","22":"雅歌","23":"以赛亚书","24":"耶利米书","25":"耶利米哀歌","26":"以西结书","27":"但以理书","28":"何西阿书","29":"约珥书","30":"阿摩司书","31":"俄巴底亚书","32":"约拿书","33":"弥迦书","34":"那鸿书","35":"哈巴谷书","36":"西番雅书","37":"哈该书","38":"撒迦利亚","39":"玛拉基书","40":"马太福音","41":"马可福音","42":"路加福音","43":"约翰福音","44":"使徒行传","45":"罗马书","46":"歌林多前书","47":"歌林多后书","48":"加拉太书","49":"以弗所书","50":"腓立比书","51":"歌罗西书","52":"帖撒罗尼迦前书","53":"帖撒罗尼迦后书","54":"提摩太前书","55":"提摩太后书","56":"提多书","57":"腓利门书","58":"希伯来书","59":"雅各书","60":"彼得前书","61":"彼得后书","62":"约翰一书","63":"约翰二书","64":"约翰三书","65":"犹大书","66":"启示录"}

**Comment by Llewellynvdm** [comment]
Thank you, okay I have now added the book names to the builder, please check if they are correct:

https://github.com/getbible/v2_builder/blob/staging/conf/books_cns.json
https://github.com/getbible/v2_builder/blob/staging/conf/books_cnt.json
https://github.com/getbible/v2_builder/blob/staging/conf/books_cus.json
https://github.com/getbible/v2_builder/blob/staging/conf/books_cut.json

I will try to adapt the builder next week to start using these new files.

**Comment by missweizhang** [comment]
Hello, I made a few mistakes (I used google translate but the mapping between Traditional Chinese and Simplified Chinese is not one-to-one).  I double checked against Biblegateway and here's the corrected version: (corrected 38, 46, 47)

Traditional Chinese
{"1":"﻿創世記","2":"出埃及記","3":"利未記","4":"民數記","5":"申命記","6":"約書亞記","7":"士師記","8":"路得記","9":"撒母耳記上","10":"撒母耳記下","11":"列王紀上","12":"列王紀下","13":"歷代志上","14":"歷代志下","15":"以斯拉記","16":"尼希米記","17":"以斯帖記","18":"約伯記","19":"詩篇","20":"箴言","21":"傳道書","22":"雅歌","23":"以賽亞書","24":"耶利米書","25":"耶利米哀歌","26":"以西結書","27":"但以理書","28":"何西阿書","29":"約珥書","30":"阿摩司書","31":"俄巴底亞書","32":"約拿書","33":"彌迦書","34":"那鴻書","35":"哈巴谷書","36":"西番雅書","37":"哈該書","38":"撒迦利亞書","39":"瑪拉基書","40":"馬太福音","41":"馬可福音","42":"路加福音","43":"約翰福音","44":"使徒行傳","45":"羅馬書","46":"歌林多前書","47":"歌林多後書","48":"加拉太書","49":"以弗所書","50":"腓立比書","51":"歌羅西書","52":"帖撒羅尼迦前書","53":"帖撒羅尼迦後書","54":"提摩太前書","55":"提摩太後書","56":"提多書","57":"腓利門書","58":"希伯來書","59":"雅各書","60":"彼得前書","61":"彼得後書","62":"約翰一書","63":"約翰二書","64":"約翰三書","65":"猶大書","66":"启示录"}

Simplified Chinese
{"1":"﻿创世记","2":"出埃及记","3":"利未记","4":"民数记","5":"申命记","6":"约书亚记","7":"士师记","8":"路得记","9":"撒母耳记上","10":"撒母耳记下","11":"列王纪上","12":"列王纪下","13":"历代志上","14":"历代志下","15":"以斯拉记","16":"尼希米记","17":"以斯帖记","18":"约伯记","19":"诗篇","20":"箴言","21":"传道书","22":"雅歌","23":"以赛亚书","24":"耶利米书","25":"耶利米哀歌","26":"以西结书","27":"但以理书","28":"何西阿书","29":"约珥书","30":"阿摩司书","31":"俄巴底亚书","32":"约拿书","33":"弥迦书","34":"那鸿书","35":"哈巴谷书","36":"西番雅书","37":"哈该书","38":"撒迦利亚书","39":"玛拉基书","40":"马太福音","41":"马可福音","42":"路加福音","43":"约翰福音","44":"使徒行传","45":"罗马书","46":"哥林多前书","47":"哥林多后书","48":"加拉太书","49":"以弗所书","50":"腓立比书","51":"歌罗西书","52":"帖撒罗尼迦前书","53":"帖撒罗尼迦后书","54":"提摩太前书","55":"提摩太后书","56":"提多书","57":"腓利门书","58":"希伯来书","59":"雅各书","60":"彼得前书","61":"彼得后书","62":"约翰一书","63":"约翰二书","64":"约翰三书","65":"犹大书","66":"启示录"}

**Comment by Llewellynvdm** [comment]
Okay I have update the files, please check again... and let me know:

https://github.com/getbible/v2_builder/blob/staging/conf/books_cns.json
https://github.com/getbible/v2_builder/blob/staging/conf/books_cnt.json
https://github.com/getbible/v2_builder/blob/staging/conf/books_cus.json
https://github.com/getbible/v2_builder/blob/staging/conf/books_cut.json

**Comment by Llewellynvdm** [comment]
Here you can see what changed:

https://github.com/getbible/v2_builder/commit/945c877c723b79919753621c2ecdea043152b2b1

**Comment by missweizhang** [comment]
thanks!

**Comment by missweizhang** [comment]
Thank you so much!

**Comment by Llewellynvdm** [comment]
My pleasure, I should have it added into the actual API soon.

**Comment by Llewellynvdm** [comment]
### Centralizing Support to a Single Location

We're excited to share that we've streamlined our support process for all GetBible projects to a single repository for greater efficiency and quicker response times. You can access this at: https://git.vdm.dev/getBible/support

Consequently, we'll be closing this issue here. Should you wish to respond, or if you encounter any new issues, kindly utilize the new Support Repository. We're confident this will help us respond to your concerns in a more timely manner.

Thank you for your understanding and continued support!
