### ISSUE TITLE
Strong numbers have disappeared

### ISSUE THREAD

**Issue by nicolasrhone** [getbible/v2#13]
In v1, we had access to strong numbers in some versions... They disappeared in v2, making it incompatible.

**Comment by Llewellynvdm** [comment]
I will have to look into this, as I am not sure why the STRONG numbers are not exported from the Crowsswire models.

**Comment by Llewellynvdm** [comment]
### Centralizing Support to a Single Location

We're excited to share that we've streamlined our support process for all GetBible projects to a single repository for greater efficiency and quicker response times. You can access this at: https://git.vdm.dev/getBible/support

Consequently, we'll be closing this issue here. Should you wish to respond, or if you encounter any new issues, kindly utilize the new Support Repository. We're confident this will help us respond to your concerns in a more timely manner.

Thank you for your understanding and continued support!
