### ISSUE TITLE
Confused about API changes.

### ISSUE THREAD

**Issue by enveezee** [getbible/v2#14]
I just typed a bible citation in my channel and my bot didnt respond I determined it is because your site is currently offline, however in discovering that I saw mention of an API change that supposedly was a required change to be made by end of 2021. Here is the thing, I wrote my code two years ago and it has been working just fine for the last two years. What I coded doesn't seem to match either your V2 api OR your legacy API, so it would seem your documentation is incorrect. Here is my project https://github.com/enveezee/INRI and if any changes need be make and you can make them, please feel free to do so, and if not, if ya can just tell me what the real deal is, I can fix it myself when I get a moment. Line 210 of plugin.py is where I have url = f'http://getbible.net/json?p={p}&v={v}'   I don't see any api format like that anywhere on your github.

**Comment by Llewellynvdm** [comment]
Greetings, the notice was added in 2018... that we would end that API end of 2021... and it is now 2023

I am truly sorry that announcement this could not be done clearer, and helped avoid causing you this discomfort.

In reality, we've needed to overhaul our API for years. However, due to my preoccupation with numerous tasks, it kept being postponed. The API you've been interfacing with—more specifically, the endpoint you've been using—is a PHP endpoint that's heavily reliant on a database and highly resource-intensive. Consequently, we had to initiate several crucial modifications.

The most significant one was transitioning our API to static files, thereby enabling it to be easily distributed via content distribution networks and hosted at various locations. This modification was vital to accommodate the API's increasing usage. Thus, this was a paramount objective.

As a result of these modifications, we were only able to implement them for entire translations—books in translations, and chapters within those books. Breaking it down to verse levels seemed excessive, as users rarely ever call for a single verse. More often, they request a series of verses, typically spanning across books or chapters, which requires a more dynamic approach. 

Therefore, we decided to not only upgrade the API but also the application that serves the verse layer of the API. We plan to release this application next week, and it will reintroduce an endpoint that can be used to obtain more granular portions of scripture. However, its format has also been altered—primarily not the query format but the return values. The new presentation now aligns more with the new API, version 2.

If you examine the structure of the verses in the chapters in that API, you'll notice that we've made an effort to conform to this version 2 format of the JSON object being returned. God willing, we'll launch the new application next week, which will allow for this granular paragraph request that you're currently utilizing. However, it will come with a change in format. 

I'm uncertain whether I'll have the time to offer a version 1 format as an alternative within this app. The new application is, once again, a Joomla PHP application that can be installed on a Joomla website. It's a significant improvement over the previous application. If you look at the GetBible homepage, it was a JavaScript-driven (specifically jQuery AJAX) application. We've transitioned away from this approach—albeit not entirely. We still use AJAX in some ways but have moved to an application that delivers scripture via a URL request. You can input the translation, book name, and chapter, and get the scripture directly from the URL. 

This advancement enables easier scripture sharing and signifies a substantial improvement in the application layer and the API implementation. The new app, launching next week, offers these benefits, among many others. This app was the main reason for the change. Additionally, it will reintroduce an API endpoint on GetBible.

There will be a new API endpoint to request parts of scripture, which is currently lacking from the static API setup we have in place. If you're planning to make changes, this would be the direction to consider. Although I can (let me know if ou would want this) temporarily reactivate the old API for you, it will only be available for this week. They can't coexist on the same domain or system. Therefore, when the new API is implemented, you'll again be faced with an error. 

You should start considering the necessary changes to your application so that it can accommodate the new API. I can provide you with some documentation on how the new API endpoint will function and appear, if that would be helpful. Let me know.

Again, I sincerely apologize for not getting this message to you sooner. The transition notice from the current API to version 2 has been available on GitHub for quite some time. I understand that many may not have made the shift because the version 2 static files do not support granular verse selection. I was only able to address this issue last week while manually revamping the application.

I sincerely hope that the modifications we've made, the new API, and the new application will serve your purposes and be usable in your project. Please let me know if you'd like to see some documentation, and if you're willing to join me on this journey to the new API. Thank you.

**Comment by Llewellynvdm** [comment]
I have moved the old system to `https://archived.getbible.net/` and it should work as before, this should give you time to move over to the new system while your application can still use the old access points.

So you should be able to use:
```
https://archived.getbible.net/json?passage=1Jn3:16
```

> So from the moment the new system is up and running and we have the new API documented, we will keep the ARCHIVED system for 6 months, and then we will completely remove it. This means you will have six months from the moment we have the new API up and running to move over to the new API.

**Comment by Llewellynvdm** [comment]
We hope to release the new verse range API **July 31th**

I will update this tread one its ready.

**Comment by enveezee** [comment]
Sounds good, I understand where you're coming from with the resource usage. I guess I will have to wait and see what changes I would need to make. The archive thing is working. I don't use it terribly often was just one of those things I thought would be nice to have. I was bored two years ago on easter sunday and had coded that plugin so that when you cite scriptures in chat, it would pull them up. None of the bible plugins I could find even functioned anymore and none offered the ability to automatically pull up citations any time someone mentions them. I went looking for a suitable API to use, and was pleased when I found yours and it didn't require an API key. API keys are useful for the kinds of things you mentioned, it allows you to only grant access to people who have a key and then be able to revoke or limit those users if you run into issues. However from a user standpoint, it makes things more complicated having to request a key and set it in the application. In any case, thanks for the work, its a good resource for accessing scriptures programmatically.

**Comment by Llewellynvdm** [comment]
### Centralizing Support to a Single Location

We're excited to share that we've streamlined our support process for all GetBible projects to a single repository for greater efficiency and quicker response times. You can access this at: https://git.vdm.dev/getBible/support

Consequently, we'll be closing this issue here. Should you wish to respond, or if you encounter any new issues, kindly utilize the new Support Repository. We're confident this will help us respond to your concerns in a more timely manner.

Thank you for your understanding and continued support!
