### ISSUE TITLE
Question : Is it possible to get mulitple chapters at once?

### ISSUE THREAD

**Issue by JoshuaCrewe** [getbible/v2#3]
I suspect the answer is no ... but say I wanted Genesis 1-6 in one request, is that possible?

Thanks for open sourcing this API, it is helpful to see working.

**Comment by Llewellynvdm** [comment]
Not yet, at this point you can only get them one chapter or the whole book, or the whole version. I am working on a new dynamic API for years now... just like everything is keeping me away from completing this. But I am working on it, on weekends and other moments.

**Comment by JoshuaCrewe** [comment]
That’s cool. What you have so far is amazing!

Do you have rate limiting in place? That’s the kicker in this scenario. Chapters 1-6 is six http requests which could amp up the demand on the server.

Is there anything specific you need help on right now?

**Comment by Llewellynvdm** [comment]
If you can learn how to work with [JCB](https://github.com/vdm-io/Joomla-Component-Builder), that that would be amazing... lol

There in no limit, just the servers own limits.

**Comment by JoshuaCrewe** [comment]
Is Joomla still going is it?! As in the CMS?

I am having trouble figuring out this repo, where is the data coming from and how are the requests handled? All I can see are sha hashes and organisational Json. Is the business logic in another repo?

**Comment by Llewellynvdm** [comment]
This repo is just the values used to identify changes to the Scripture, since if Cross-wire push out a fix, these hashes will update, so you can know to update your script that is based on this API.

The API itself as you may know is at https://getbible.net/v2/translations.json which gives you the list of translations, and then when calling any of the give urls like: https://getbible.net/v2/kjv.json you get the whole translation, or for a book: https://getbible.net/v2/kjv/1.json or a chapter: https://getbible.net/v2/kjv/1/1.json

That is all the API does for now, we have an API build for Joomla, and I told you about JCB since I am rebuilding the dynamic API that can return only parts, and combination of scripture with JCB.

So learning JCB would be the only way to get involved in the dynamic API which I am still working on :+1: 

Joomla is far more then a CMS, it is indeed the cloud app of the future... lol

**Comment by JoshuaCrewe** [comment]
Thanks for the response. I guess I can’t really see how the api and the data are connected. So when I hit an end point for a chapter it will give me the verses in thy chapter. Is that functionality in another repo or private or something?

I am going to close this because you have answered my question. Thanks for that!

**Comment by Llewellynvdm** [comment]
This API is not database driven, but static file driven. That means the JSON is already build and you are download the static file. This makes it extremely fast and absolutely stable.

**Comment by Llewellynvdm** [comment]
I am using a python script to update the files every so often from the Cross-wire modules of each translation.
