### ISSUE TITLE
Random Bible Verse

### ISSUE THREAD

**Issue by cephox** [getbible/v2#5]
Please add the functionality to retrieve a random bible verse.

**Comment by Llewellynvdm** [comment]
We are working on a new dynamic API.

But V2 API is only static, and will can only as the smallest unit call chapters, not verses. 

These are the URL's to get for example chapter 1 and 2 of the book of John.
```
https://getbible.net/v2/kjv/43/1.json
```
And
```
https://getbible.net/v2/kjv/43/2.json
```
Then store this in the browser database: https://javascript.info/indexeddb, and with your own Javascript make your own more direct query internal of the random verses. You can also instead of the chapters, get books, or whole translations.

For The whole book of John
```
https://getbible.net/v2/kjv/43.json
```
Or the whole KJV
```
https://getbible.net/v2/kjv.json
```

You will only update the scripture then in the browser if the user clears their browser memory, or if the file [hash changes](https://getbible.net/v2/kjv/43/checksum.json), since each return set has a hash. This is used to keep the repository in sync with the [Crosswire modules](http://www.crosswire.org/sword/modules/ModDisp.jsp?modType=Bibles), since they maintain the integrity of the scripture as a community.

Please read over this repository main [readme](https://github.com/getbible/v2/blob/master/README.md), file.
