### ISSUE TITLE
Cannot handle passage cross chapter boundary

### ISSUE THREAD

**Issue by martinmts** [getbible/v2#6]
Use `https://getbible.net/json?p=John1:51-2:1` will get `John 1:2-51`.

**Comment by Llewellynvdm** [comment]
The URL is the old API, and is no longer maintained. We are working on a new API. The V2 API is only static, and will can only as the smallest unit call chapters, not verses. This is the URL's to use with the new V2 API:
```
https://getbible.net/v2/kjv/43/1.json
```
And
```
https://getbible.net/v2/kjv/43/2.json
```
Then store this in the browser database: https://javascript.info/indexeddb, and with your own Javascript make your own more direct query of the verses.

You will only update these chapters if the user clears their browser memory, or if the file [hash changes](https://getbible.net/v2/kjv/43/checksum.json), since each return set has a hash. This is used to keep the repository in sync with the [Crosswire modules](http://www.crosswire.org/sword/modules/ModDisp.jsp?modType=Bibles), since they maintain the integrity of the scripture as a community.

Please read over this repository main [readme](https://github.com/getbible/v2/blob/master/README.md), file.
