### ISSUE TITLE
Language Request : Please add more Indian Languages

### ISSUE THREAD

**Issue by dcdunkan** [getbible/v2#9]
I tried to contact you for this through email, but it says email forwarding to your domain failed. That is why I came through here.

Out there Bible is available in Indian Languages such as Hindi, Malayalam, Tamil, Kannada and Telugu. I found their json files. But, all of them are as just one file. If you can, please add it to the API please. Mainly, Malayalam and Hindi.

Anyway, thankyou for your this great api. It is too much useful. Sorry to make this request through here.
I found many Indian Languages here as json file: https://github.com/godlytalias/Bible-Database

**Comment by Llewellynvdm** [comment]
Hi, nice [App you made](https://github.com/dcdunkan/bible-bot)... I have a look at it on Telegram...

I build [this little bot](https://github.com/trueChristian/telegram_bot_scripts) and use the Crosswire modules directly as [seen here](https://github.com/trueChristian/telegram_bot_scripts/blob/main/cron_daily_scripture.sh#L92). I have been look at this [bot as a solution](https://github.com/topkecleon/telegram-bot-bash) to posting any scripture into any are of Telegram. But it seems like it will take some work, and I have not had the time yet... but soon.

Hmm about your question, here is the deal, we do not use any source/host besides Crosswire at this time. There are many reasons, but the most simple one is I don't have the time to maintain the integrity of the API, so I rely completely on the Crosswire project's modules (they have a large community who are actively maintaining the digital integrity of the Scriptures). Here is a [list of all their translations](https://crosswire.org/sword/modules/ModDisp.jsp?modType=Bibles)... let me know which you think I should still add... as there are many I have not yet done, but I am willing to add more, so let me know.

**Comment by dcdunkan** [comment]
@Llewellynvdm Hi. Thankyou for the reply and for the appreciation.
As you told: here is the one you can add. [Malayalam](https://crosswire.org/sword/modules/ModInfo.jsp?modName=Mal1910). It is the main one I needed 😁.

Thankyou again for the time you spent on doing this work. I will be closing this li'l "issue" here. I will be checking for updates at the your translation list. You're bot looks nice. 

And I believe you added/removed one translation recently 😃. Great. My bot had a issue😁 for listing translations. Fixed.

**Comment by Llewellynvdm** [comment]
What is the direction of this text?

**Comment by dcdunkan** [comment]
LTR

**Comment by Llewellynvdm** [comment]
> LTR

I just ran the build and added the Translation, but the module says it is RTL... not sure if this is an error. Please forgive me... but can you give me the documentation, since I do not want to force the LTR unless I am absolutely sure we are correctly understanding the question. So you need to show me a website in this language so I can see how it looks like. (must be an official trusted website)

**Comment by Llewellynvdm** [comment]
Here is the whole translation https://getbible.net/v2/mal1910.json

**Comment by Llewellynvdm** [comment]
Okay so I found this https://en.wikipedia.org/wiki/Malayalam_script and your right.... :+1: 

Hmmm now how to fix this as I see we have a language abbreviation conflict.

I have opened the [compiler](https://github.com/getbible/v2_builder) to the public... you can see how the JSON text is build.

So we are using this [file](https://github.com/getbible/v2_builder/blob/master/conf/textDirection.json) for the RTL languages, and over here on [line 72](https://github.com/getbible/v2_builder/blob/master/src/sword_to_json.py#L72) we are setting the direction. So since the language abbreviation is `mal` is in that list... we get a false positive. I am still not sure why I added it, but I am looking into this as we speak... will try to resolve this as soon as possible.

**Comment by dcdunkan** [comment]
Yeh sir. The compiler looks great! Too easy to create files. And a happy news: Malayalam automatically added 😁. Thankyou very much. You are doing a great job sir. Anyway thankyou again. Should I close this issue? 🤔

**Comment by Llewellynvdm** [comment]
Okay the translation https://getbible.net/v2/mal1910.json is not correct. Blessings!!!

**Comment by dcdunkan** [comment]
> Okay the translation https://getbible.net/v2/mal1910.json is not correct. Blessings!!!

In **not** correct? 😳

**Comment by Llewellynvdm** [comment]
oops typo, I meant:

> is now correct... :+1: Blessings!!!

**Comment by dcdunkan** [comment]
Alright. Thankyou again!
